## ***Intall NumPy***

In [ ]:
!pip install numpy

In [ ]:
!pip install scipy

In [ ]:
import numpy as np
from scipy import sparse

## ***Creating a Vector***

In [ ]:
row_vector = np.array([1, 2, 3])
col_vector = np.array([[1],
                      [2],
                      [3]])
print(row_vector)
print(col_vector)

## ***Creating a Matrix***

In [ ]:
matrix = np.array([[1, 2],
                   [1, 2],
                   [1, 2]])
matrix

In [ ]:
martix_object = np.mat([[1, 2],
                        [1, 2],
                        [1, 2]])
martix_object

## ***Creating a Sparse Matrix***

In [ ]:
matrix = np.array([[0, 0],
                   [0, 1],
                   [3, 0]])
sparse_mat = sparse.csr_matrix(matrix)
print(sparse_mat)

In [ ]:
mat_large = np.array([[0, 0, 0, 0, 0, 0],
                      [0, 1, 0, 0, 0, 0],
                      [3, 0, 0, 0, 0, 0]])
sparse_mat_large = sparse.csr_matrix(mat_large)
print(sparse_mat_large)

  (1, 1)	1
  (2, 0)	3


##  ***Preallocating/prefilled NumPy Arrays***

In [ ]:
vector = np.zeros(shape=5)
vector

array([0., 0., 0., 0., 0.])

In [ ]:
matrix = np.full(shape=(3,3), fill_value=1)
matrix

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

## ***Selecting Elements***

In [ ]:
# Create row vector
vector = np.array([1, 2, 3, 4, 5])

# Select third element of vector
vector[2]

3

In [ ]:
# Create matrix
matrix = np.array([[1, 2, 3],
                   [2, 3, 4],
                   [3, 4, 6]])

# Select second row, second column
matrix[1,1]

3

In [ ]:
# Create row vector
vector = np.array([1, 2, 3, 4, 5])

# Select all elements of a vector
vector[:]

array([1, 2, 3, 4, 5])

In [ ]:
# Select everything up to and including the third element
vector[:3]

array([1, 2, 3])

In [ ]:
# Select everything after the third element
vector[3:]

array([4, 5])

In [ ]:
# Select the last element
vector[-2]

4

In [ ]:
# Reverse the vector
vector[::-1]

array([5, 4, 3, 2, 1])

In [ ]:
# Select the first two rows and all columns of a matrix
matrix[:2,:]

array([[1, 2, 3],
       [2, 3, 4]])

In [ ]:
# Select all rows and the second column
matrix[:,1:2]

array([[2],
       [3],
       [4]])

## ***Finding the Maximum and Minimum Values***

In [ ]:
matrix = np.array([[1, 2, 3],
                   [2, 5, 7],
                   [4, 8, 9]])

In [ ]:
np.max(matrix)

9

In [ ]:
np.min(matrix)

1

## ***Calculating the Average, Variance, and Standard Deviation***

In [ ]:
matrix = np.array([[1, 2, 3],
                    [4, 5, 6],
                    [7, 8, 9]])

In [ ]:
# Return mean
np.mean(matrix)


5.0

In [ ]:
# Return variance
np.var(matrix)


6.666666666666667

In [ ]:
# Return standard deviation
np.std(matrix)


2.581988897471611

## ***Reshaping Arrays***

In [ ]:
# Create 4x3 matrix
matrix = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9],
                   [10, 11, 12]])

In [ ]:
# Reshape matrix into 2x6 matrix
reshaped_matrix = matrix.reshape(2, 6)
print(reshaped_matrix)

[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]]


In [ ]:
matrix.reshape(1, -1)


array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12]])

## ***Transposing a Vector or Matrix***

In [ ]:
# Create matrix
matrix = np.array([[1, 2, 3],
                  [4, 5, 6],
                  [7, 8, 9]])


In [ ]:
# Transpose matrix
matrix.T

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [ ]:
# Transpose vector
vector = np.array([[1, 2, 3, 4, 5, 6]])
vector.T

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6]])

## ***Flattening a Matrix***

In [ ]:
# Create matrix
matrix = np.array([[1, 2, 3],
                    [4, 5, 6],
                    [7, 8, 9]])


In [ ]:
# Flatten matrix
matrix.flatten()


array([1, 2, 3, 4, 5, 6, 7, 8, 9])

## ***Diagonal of a Matrix***

In [ ]:
# Create matrix
matrix = np.array([[1, 2, 3],
                  [4, 5, 6],
                  [7, 8, 9]])

In [ ]:
matrix.diagonal()

array([1, 5, 9])

## ***Trace of a Matrix***

In [ ]:
# Create matrix
matrix = np.array([[1, 2, 3],
                  [4, 5, 6],
                  [7, 8, 9]])

In [ ]:
matrix.trace()

15

In [ ]:
sum(matrix.diagonal())

15

## ***Dot Products***

In [ ]:
a = np.array([1,2,3])
b = np.array([4,5,6])

In [ ]:
np.dot(a, b)

32

In [ ]:
a @ b

32

## ***Adding and Subtracting Matrices***

In [ ]:
matrix_a = np.array([[1, 1, 1],
                     [1, 1, 2],
                     [1, 1, 1]])

matrix_b = np.array([[1, 3, 1],
                     [1, 3, 2],
                     [1, 3, 1]])

In [ ]:
#adding
np.add(matrix_a, matrix_b)

array([[2, 4, 2],
       [2, 4, 4],
       [2, 4, 2]])

In [ ]:
# Subtracting
np.subtract(matrix_a, matrix_b)

array([[ 0, -2,  0],
       [ 0, -2,  0],
       [ 0, -2,  0]])

In [ ]:
# Adding
matrix_a + matrix_b

array([[2, 4, 2],
       [2, 4, 4],
       [2, 4, 2]])

## ***Multiplication of Matrices***

In [ ]:
matrix_a = np.array([[1, 1],
                    [1, 2]])

matrix_b = np.array([[1, 2],
                    [1, 3]])

In [ ]:
np.dot(matrix_a, matrix_b)

array([[2, 5],
       [3, 8]])

In [ ]:
matrix_a @ matrix_b

array([[2, 5],
       [3, 8]])

In [ ]:
# Element-wise multiplication
matrix_a * matrix_b

array([[1, 2],
       [1, 6]])

## ***Generating Random Values***

In [ ]:
# Set seed
np.random.seed(0)

In [ ]:
# Generate three random floats between 0.0 and 1.0
np.random.random(5)

array([0.54488318, 0.4236548 , 0.64589411, 0.43758721, 0.891773  ])

In [ ]:
# Generate three random integers between 0 and 10
np.random.randint(0, 11, 4)

array([6, 7, 7, 8])

In [ ]:
# Numbers greater than or equal to 1.0 and less than 2.0
np.random.uniform(1.0, 2.0, 3)

array([1.3927848 , 1.83607876, 1.33739616])